---
type_regex: !!map
  deposit: "(^TransferGoGrowMainRepaiment.*)"
  withdraw: "(^TransferWithdraw*)"
  interest: "(^TransferGoGrowInterestRepaiment$)"
  fee: "(^GoGrowWithdrawalFee$)"

csv_fieldnames:
  booking_date: 'TransferDate'
  booking_date_format: '%d.%m.%Y %H:%M'
  booking_details: 'Description'
  booking_id: 'LoanNumber'
  booking_type: 'Description'
  booking_value: 'Amount'
  booking_currency: 'Currency'
