---
type_regex: !!map
  deposit: "^Deposit.*"
  withdraw: "^Withdrawal.*"
  interest: "(^Interest.*)|(^Indemnity.*)|(^Referral.*)|(^EG Bonus.*)|(^Secondary Market Profit.*)"
  fee: "(^Secondary Market Loss.*)|(^Fee.*)"

csv_fieldnames: !!map
  booking_date: 'Payment Date'
  booking_date_format: '%d/%m/%Y %H:%M'
  booking_details: 'Loan Code'
  booking_id: 'ID'
  booking_type: 'Cash Flow Type'
  booking_value: 'Amount'
  booking_currency: 'Currency'
